version: "3"

services:
  contenuxt:
    build:
      context: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/app
      - /app/node_modules/
    env_file:
      - .env
    container_name: contenuxt